title: Kevin Oliveira
subtitle: >
          @kvnol
email: me@kevinoliveira.com.br
description: Front-end, UX/UI padawan and pseudo-musician.
baseurl: ""
url: "http://kevinoliveira.com.br/"
user: kvnol

# Build settings
markdown: kramdown

sass:
  sass_dir: assets/_sass
  style: compressed