title: Kevin Oliveira
email: me@kevinoliveira.com.br
description: >
  Front-end, UX and musician. Work at Insane.
baseurl: ""
url: "http://kevinoliveira.com.br/"
user: kvnol

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
